on:
  workflow_dispatch:

jobs:
  generate_tile:
    runs-on: ubuntu-latest
    container: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    steps:
    
    - name: Generate Tile
      run: |
        sudo apt install wget -y
        wget https://download.geofabrik.de/north-america/us/south-carolina-latest.osm.pbf
        mkdir -p valhalla_tiles
        valhalla_build_config > valhalla.json
        valhalla_build_tiles -c valhalla.json south-carolina-latest.osm.pbf
