on:
  workflow_dispatch:

jobs:
  generate_tile:
    runs-on: ubuntu-latest
    container: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    steps:
    
    - name: Download Dependencies
      run: sudo apt install wget -y
        
    - name: Download OSM PBF
      run: sudo wget -q https://download.geofabrik.de/north-america/us/south-carolina-latest.osm.pbf
      
    - name: Mjolnir Build
      run: |
        sudo valhalla_build_config | sudo tee -a valhalla.json
        sudo valhalla_build_extract -c valhalla.json south-carolina-latest.osm.pbf
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: valhalla_tiles
        path: /data/valhalla/valhalla_tiles.tar
