on:
  workflow_dispatch:

jobs:
  generate_tile:
    runs-on: ubuntu-latest
    container: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    steps:
    
    - name: Download Dependencies
      run: sudo apt install wget -y
        
    - name: Download OSM PBF
      run: sudo wget -q https://download.geofabrik.de/north-america/us/south-carolina-latest.osm.pbf
      
    - name: Start Mjolnir Build    
      run: |
        sudo valhalla_build_config | sudo tee -a valhalla.json
        sudo valhalla_build_tiles -c valhalla.json south-carolina-latest.osm.pbf
        
    - name: Tar Archive Valhalla Tiles
      run: sudo tar -cf valhalla_tiles.tar -C /data/valhalla/ .
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: valhalla_tiles
        path: ./valhalla_tiles.tar
