name: Automatic Tile Generation and Release

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - README.md

  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - README.md
  
  workflow_dispatch:
  
jobs:
  generate_tile:
    runs-on: ubuntu-latest
    container: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    steps:
    
    - name: Download Dependencies
      run: sudo apt install wget -y
    
    # Note that this is hardcoded to download and generate tile only for South Carolina at the moment
    - name: Download OSM PBF
      run: sudo wget -q https://download.geofabrik.de/north-america/us/south-carolina-latest.osm.pbf
      
    - name: Mjolnir Build
      run: |
        sudo valhalla_build_config | sudo tee -a valhalla.json
        sudo valhalla_build_tiles -c valhalla.json south-carolina-latest.osm.pbf
        sudo valhalla_build_extract -c valhalla.json

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: tiles
        path: /data/valhalla/tiles.tar

    - name: Create Automatic Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        automatic_release_tag: latest
        files: /data/valhalla/tiles.tar
